### ISSUE TITLE
user tidak masuk database waktu daftar

### ISSUE THREAD

**Issue by cluster777** [2018-PemrogramanWeb-B/tugas7-fp-ar-15_best_raifu#3]
![image](https://user-images.githubusercontent.com/42055002/50206679-bcdfa400-039e-11e9-8337-be2540c7f0f8.png)
waktu daftar
![image](https://user-images.githubusercontent.com/42055002/50206702-cf59dd80-039e-11e9-9c8f-465dce75a2f0.png)
database

mengakibatkan error boolean pada fetch assoc di login

**Comment by sudrajadhadi** [comment]
udah di edit
